config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'welcome#index', as: 'root'

  namespace :admin do
    resources :categories, except:[:new]
    resources :images, except:[:new, :show]
  end

  resources :users, only:[:new, :create]

  resources :users, only:[:show] do
    resources :ideas
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :title, :content

  belongs_to :user
  belongs_to :category
  has_many :idea_images, dependent: :destroy
  has_many :images, through: :idea_images
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :url, :alt_tag

  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :first_name, :last_name, :email, :password
  validates_uniqueness_of :email

  has_many :ideas

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private
    def require_admin
      render file: 'public/404' unless current_admin?
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @category = Category.new()
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Success"
    end
    redirect_to admin_categories_path
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  before_action :set_image, only: [:edit, :update, :destroy]

  def index
    @images = Image.all
    @image = Image.new()
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "Success"
      redirect_to admin_images_path
    end
  end

  def edit
  end

  def update
    @image.update(image_params)
    redirect_to admin_images_path
  end

  def destroy
    @image.destroy
    redirect_to admin_images_path
  end

  private

    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:url, :alt_tag)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_default?
    current_user && current_user.default?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new()
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Success"
    end
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :verify_user
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  def index
    @ideas = current_user.ideas
  end

  def show
  end

  def new
    @categories = Category.all
    @images = Image.all
    @idea = current_user.ideas.new()
  end

  def create
    @idea = current_user.ideas.new(idea_params)
    if @idea.save
      params[:idea][:image_ids].each do |id|
        @idea.idea_images.create(image_id: id.to_i)
      end
      flash[:notice] = "Success"
      redirect_to user_idea_path(current_user, @idea)
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    @images = Image.all
  end

  def update
    if @idea.update(idea_params)
      @idea.idea_images.destroy_all
      params[:idea][:image_ids].each do |id|
        @idea.idea_images.create(image_id: id.to_i)
      end
      flash[:notice] = "Success"
      redirect_to user_idea_path(current_user, @idea)
    else
      render :edit
    end
  end

  def destroy
    current_user.ideas.destroy(params[:id])
    redirect_to user_ideas_path(current_user)
  end

  private
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def verify_user
      unless current_user.id.to_s == params[:user_id]
        flash[:notice] = "Stick to your own ideas!"
        redirect_to user_path(current_user)
      end
    end

    def idea_params
      params.require(:idea).permit(:title, :content, :category_id, :user, :image_ids)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @image = Image.new()
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "Success"
      redirect_to images_path
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.update(image_params)
    redirect_to images_path
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:url, :alt_tag)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "welcome_layout"

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "welcome_layout", only:[:new]

  def show
    @user = current_user
    if current_admin?
      render :admin_show
    else
      render :show
    end
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome_layout"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h2>Edit <%= @category.name %></h2>

<%= render partial: "form" %>

app/views/admin/categories/index.html.erb
<h2>Categories</h2>

<section class="grid">
  <% @categories.each do |category| %>
    <div class="grid-cell">
      <h3><%= link_to category.name, admin_category_path(category) %></h3>
      <p><%= link_to "Edit", edit_admin_category_path(category) %> - <%= link_to "Delete", admin_category_path(category), method: :delete %></p>
    </div>
  <% end %>
</section>

<footer>
  <h3>New Category</h3>
  <%= render partial: "form" %>
</footer>

app/views/admin/categories/show.html.erb
<h2><%= @category.name %></h2>

<p><%= link_to "Edit", edit_admin_category_path(@category) %> - <%= link_to "Delete", admin_category_path(@category), method: :delete %></p>

app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image] do |f| %>
  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div>
    <%= f.label :alt_tag %>
    <%= f.text_field :alt_tag %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<h2>Edit Image</h2>

<%= render partial: "form" %>

app/views/admin/images/index.html.erb
<h2>Images</h2>

<section class="grid">
  <% @images.each do |image| %>
    <div class = "image-cell">
      <p><%= link_to "Edit", edit_admin_image_path(image) %> - <%= link_to "Delete", admin_image_path(image), method: :delete %></p>
      <img src="<%= image.url %>">
      <p><%= image.alt_tag %></p>
    </div>
  <% end %>
</section>

<footer>
  <h3>Add Image</h3>
  <%= render partial: "form" %>
</footer>

app/views/ideas/_form.html.erb
<%= form_for [current_user, @idea] do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div><br>

  <div>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div><br>

  <div>
    <%= f.label :category %><br>
    <%= f.collection_select(:category_id, @categories.order(:name), :id, :name) %>
  </div><br>

  <div>
    <%= f.label "Select Image(s):" %>
    <%= f.collection_check_boxes :image_ids, @images.order(:alt_tag), :id, :alt_tag do |t| %>
      <ul>
        <%= t.check_box %> <%= t.label %>
      </ul>
    <% end %>
  </div><br>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h2>Edit '<%= @idea.title %>'</h2>

<%= render partial: "form" %>

app/views/ideas/index.html.erb
<h2><%= current_user.first_name %>'s Ideas</h2>

<% if @ideas.empty? %>
  <p>Log your first travel dream by clicking 'New Idea' below!</p>
<% end %>

<section class="grid" >
  <% @ideas.each do |idea| %>
    <div class="grid-cell">
      <p><%= idea.category.name %></p>
      <h3><%= link_to idea.title, user_idea_path(current_user, idea) %></h3>
      <p><%= link_to "Edit", edit_user_idea_path(current_user, idea) %> - <%= link_to "Delete", user_idea_path(current_user, idea), method: :delete %></p>
    </div>
  <% end %>
</section>

<footer>
  <h3><%= link_to "New Idea", new_user_idea_path(current_user) %></h3>
</footer>

app/views/ideas/new.html.erb
<h2>New Idea</h2>

<%= render partial: "form" %>

app/views/ideas/show.html.erb
<h2><%= @idea.title %> - <%=@idea.category.name%></h2>
<p><%= link_to "Edit", edit_user_idea_path(current_user, @idea) %> - <%= link_to "Delete", user_idea_path(current_user, @idea), method: :delete %></p>

<section class="content">
  <p class="content"><%= @idea.content %></p>
</section>

<section class="grid">
  <% @idea.images.each do |image| %>
    <img src="<%= image.url %>" alt="<%= image.alt_tag%>">
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="../../assets/stylesheets/main.scss">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>Travel Box</h1>
      <nav>
        <% if current_user.admin? %>
          <p><%= link_to "My Dashboard", user_path(current_user) %></p>
          <p><%= link_to "My Ideas", user_ideas_path(current_user) %></p>
          <p><%= link_to "Categories", admin_categories_path %></p>
          <p><%= link_to "Images", admin_images_path%></p>
          <p><%= link_to "Log Out", logout_path, method: :delete%></p>
        <% else %>
          <p><%= link_to "My Dashboard", user_path(current_user) %></p>
          <p><%= link_to "My Ideas", user_ideas_path(current_user) %></p>
          <p><%= link_to "Log Out", logout_path, method: :delete%></p>
        <% end %>
      </nav>
    </header>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/logout_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="../../assets/stylesheets/main.scss">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>Travel Box</h1>
      <nav>
        <p><%= link_to "Log Out", logout_path, method: :delete %></p>
      </nav>
    </header>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="../../assets/stylesheets/main.scss">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1><%= link_to "Travel Box", root_path %></h1>
      <nav>
        t
      </nav>
    </header>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div><br>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div><br>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div><br>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div><br>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div><br>

  <div>
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/admin_show.html.erb
<h2>Welcome, <%= @user.first_name %></h2>

<h3><%= link_to "Current Travel Ideas", user_ideas_path(@user) %></h3>

<h3><%= link_to "New Travel Idea", new_user_idea_path(@user) %></h3>

<h3><%= link_to "Categories", admin_categories_path %></h3>

<h3><%= link_to "Images", admin_images_path %></h3>

app/views/users/new.html.erb
<h2>Enter your information:</h2>

<%= render partial: "form" %>

app/views/users/show.html.erb
<h2>Welcome, <%= @user.first_name %></h2>

<h3><%= link_to "Current Travel Ideas", user_ideas_path(@user) %></h3>

<h3><%= link_to "New Travel Idea", new_user_idea_path(@user) %></h3>

app/views/welcome/index.html.erb
<h1>Welcome to Travel Box!</h1>

<p class="welcome-message">A place for all your trip, travel, and vacation ideas.</p>

<h3><%= link_to "Sign Up", new_user_path %> - <%= link_to "Log In", login_path %></h3>